// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bb1a22ef-1db1-4655-a41d-efe549ff4cfa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RfF49Nzbv",
    "aws_user_pools_web_client_id": "4e7j07h6i454e94h82ev1flp36",
    "oauth": {
        "domain": "testapp6c1dca01-6c1dca01-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://192.168.1.28:19000/",
        "redirectSignOut": "exp://192.168.1.28:19000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
